export enum OPENFDA_KEY_NAMES {
  "device_class" = "Device Classification",
  "regulation_number" = "Regulation Number",
  "medical_specialty" = "Regulation Medical Specialty",
  "medical_specialty_description" = "Regulation Medical Specialty",
  "review_panel" = "Regulation Review Panel",
  "definition" = "Definition",
  "description" = "Description",
  "PHYSICALSTATE" = "Physical State",
  "TECHNICALMETHOD" = "Technical Method",
  "TARGETAREA" = "Target Area",
  "gmp_exempt_flag" = "GMP Exempt",
  "life_sustain_support_flag" = "Life Sustain Support",
  "implant_flag" = "Implant",
  "third_party_flag" = "Third Party",
  "decision_code" = "Decision Code",
  "applicant" = "Applicant",
  "generic_name" = "Generic Name",
  "product_code" = "Product Code",
  "product_codes" = "Product Codes",
  "docket_number" = "Docket Number",
  "advisory_committee_description" = "Advisory Committee",
  "ao_statement" = "Approval Order Statement",
  "device_name" = "Device Name",
  "cfr_part" = "CFR (part)",
  "cfr_subpart" = "CFR (subpart)",
  "classification" = "Classification",
  "identification" = "Identification",
  "k_number" = "K number",
  "decision_date" = "Decision Date",
  "date_received" = "Date Received",
  "application_length" = "Application Length",
  "pma_number" = "PMA Number",
  "part" = "Part",
  "subpart" = "Subpart",
  "decision_description" = "Decision Description",
  "clearance_type" = "Clearance Type",
  "statement_or_summary" = "Statement or Summary?",
  "cost" = "Estimated Cost"
};

// used in links:
export enum ID_FIELD_TO_SLUG {
  "k_number" = "510k",
  "pma_number" = "pma",
  "product_code" = "product_code",
  "regulation_number" = "regulation_number"
}

export enum MEDICAL_SPECIALTY {
  "AN" = "Anesthesiology",
  "CV" = "Cardiovascular",
  "CH" = "Clinical Chemistry",
  "DE" = "Dental",
  "EN" = "Ear, Nose, Throat",
  "GU" = "Gastroenterology, Urology",
  "HO" = "General Hospital",
  "HE" = "Hematology",
  "IM" = "Immunology",
  "MI" = "Microbiology",
  "NE" = "Neurology",
  "OB" = "Obstetrics/Gynecology",
  "OP" = "Ophthalmic",
  "OR" = "Orthopedic",
  "PA" = "Pathology",
  "PM" = "Physical Medicine",
  "RA" = "Radiology",
  "SU" = "General, Plastic Surgery",
  "TX" = "Clinical Toxicology",
}